COLUMNS:
  customerID: object
  gender: object
  SeniorCitizen: int64
  Partner: object
  Dependents: object
  tenure: int64
  PhoneService: object
  MultipleLines: object
  InternetService: object
  OnlineSecurity: object
  OnlineBackup: object
  DeviceProtection: object
  TechSupport: object
  StreamingTV: object
  StreamingMovies: object
  Contract: object
  PaperlessBilling: object
  PaymentMethod: object
  MonthlyCharges: float64
  TotalCharges: object
  Churn: object

TARGET_COLUMN:
  name: Churn

COL_NAN_RATIO: 0.1

CATEGORIES:
  gender :
    - Female
    - Male
  Partner : 
    - 'Yes'
    - 'No'
  Dependents :
    - 'No'
    - 'Yes'
  PhoneService :
    - 'No'
    - 'Yes'
  MultipleLines :
    - 'No phone service'
    - 'No'
    - 'Yes'
  InternetService :
    - 'DSL'
    - 'Fiber optic'
    - 'No'
  OnlineSecurity :
    - 'No'
    - 'Yes'
    - 'No internet service'
  OnlineBackup :
    - 'Yes'
    - 'No'
    - 'No internet service'
  DeviceProtection :
    - 'Yes'
    - 'No'
    - 'No internet service'
  TechSupport :
    - 'Yes'
    - 'No'
    - 'No internet service'
  StreamingTV :
    - 'Yes'
    - 'No'
    - 'No internet service'
  StreamingMovies :
    - 'Yes'
    - 'No'
    - 'No internet service'
  Contract :
    - 'Month-to-month'
    - 'One year'
    - 'Two year'
  PaperlessBilling :
    - 'Yes'
    - 'No'
  PaymentMethod :
    - 'Electronic check'
    - 'Mailed check'
    - 'Bank transfer (automatic)'
    - 'Credit card (automatic)'
  Churn :
    - 'No'
    - 'Yes' 